import{S as u,a as h}from"./assets/vendor-B6Fq-XDb.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const l=new u(".gallery a",{captionsData:"alt",captionDelay:250});function g(e){const o=e.map(({webformatURL:a,largeImageURL:s,tags:t,likes:r,views:n,comments:y,downloads:p})=>`
      <li class="gallery-item">
        <a href="${s}">
          <img src="${a}" alt="${t}" loading="lazy" />
        </a>
        <div class="info">
        <p><span class="label">Likes</span> ${r}</p>
        <p><span class="label">Views</span> ${n}</p>
        <p><span class="label">Comments</span> ${y}</p>
        <p><span class="label">Downloads</span> ${p}</p>
      </div>
    </li>
  `).join("");document.querySelector(".gallery").insertAdjacentHTML("beforeend",o),l?l.refresh():l=new u(".gallery a").refresh()}function L(){document.querySelector(".gallery").innerHTML=""}function S(){document.querySelector(".loader").classList.remove("hidden")}function b(){document.querySelector(".loader").classList.add("hidden")}function q(){document.querySelector(".load-more").classList.remove("hidden")}function i(){document.querySelector(".load-more").classList.add("hidden")}function w(){const e=document.createElement("p");e.textContent="We're sorry, but you've reached the end of search results.",e.classList.add("end-message"),document.querySelector(".gallery").after(e)}const v="51374553-10d356351fe3cee6cad66f6b9",E="https://pixabay.com/api/",P=15;async function B(e,o=1){return(await h.get(E,{params:{key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:P}})).data}let f="",c=1,d=0;const O=document.querySelector("#search-form"),$=document.querySelector(".load-more");O.addEventListener("submit",async e=>{var a;e.preventDefault();const o=e.target.elements.searchQuery.value.trim();o&&(f=o,c=1,L(),i(),(a=document.querySelector(".end-message"))==null||a.remove(),await m())});$.addEventListener("click",async()=>{c++,await m()});async function m(){try{S();const e=await B(f,c);if(d=e.totalHits,e.hits.length===0){i();return}g(e.hits),document.querySelectorAll(".gallery-item").length>=d?(i(),w()):q(),c>1&&A()}catch(e){console.error("Error fetching images:",e)}finally{b()}}function A(){const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
