import{S as h,a as L,i}from"./assets/vendor-DhpBV7YY.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();let c;function S(e){const o=e.map(({webformatURL:a,largeImageURL:n,tags:t,likes:r,views:s,comments:g,downloads:p})=>`
      <li class="gallery-item">
        <a href="${n}">
          <img src="${a}" alt="${t}" loading="lazy" />
        </a>
        <div class="info">
        <p><span class="label">Likes</span> ${r}</p>
        <p><span class="label">Views</span> ${s}</p>
        <p><span class="label">Comments</span> ${g}</p>
        <p><span class="label">Downloads</span> ${p}</p>
      </div>
    </li>
  `).join("");document.querySelector(".gallery").insertAdjacentHTML("beforeend",o),c?c.refresh():c=new h(".gallery a",{captionsData:"alt",captionDelay:250})}function b(){document.querySelector(".gallery").innerHTML=""}function w(){document.querySelector(".loader").classList.add("visible")}function q(){document.querySelector(".loader").classList.remove("visible")}function v(){document.querySelector(".load-more").classList.remove("hidden")}function u(){document.querySelector(".load-more").classList.add("hidden")}function P(){const e=document.createElement("p");e.textContent="We're sorry, but you've reached the end of search results.",e.classList.add("end-message"),document.querySelector(".gallery").after(e)}const E="51374553-10d356351fe3cee6cad66f6b9",B="https://pixabay.com/api/",O=15;async function $(e,o=1){return(await L.get(B,{params:{key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:O}})).data}let f="",l=1,d=0;const m=document.querySelector("#search-form"),A=document.querySelector(".load-more");m.addEventListener("submit",async e=>{var a;e.preventDefault();const o=e.target.elements.searchQuery.value.trim();if(!o){i.warning({title:"Warning",message:"Please enter a search term!"});return}f=o,l=1,b(),u(),(a=document.querySelector(".end-message"))==null||a.remove(),await y(),e.target.reset(),m.elements.searchQuery.focus()});A.addEventListener("click",async()=>{l++,await y()});async function y(){try{w();const e=await $(f,l);if(d=e.totalHits,e.hits.length===0){u(),i.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"});return}S(e.hits),document.querySelectorAll(".gallery-item").length>=d?(u(),P()):v(),l>1&&M()}catch(e){i.error({title:"Error",message:"Something went wrong. Please try again later."}),console.error("Error fetching images:",e)}finally{q()}}function M(){const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
